force-app/main/default/objects/Query__mdt/Query__mdt.object-meta.xml
<CustomObject>
    <description
  >This custom metadata type holds SOQL/SOSL queries for various objects. The queries can be used in Apex Classes that do mass update/delete operations.</description>
    <label>Query</label>
    <pluralLabel>Queries</pluralLabel>
</CustomObject>

force-app/main/default/objects/Query__mdt/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <description
  >The condition field defines the WHERE-clause of the query.</description>
    <label>Condition</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Query__mdt/fields/Is_Hard_Delete__c.field-meta.xml
<CustomField>
    <fullName>Is_Hard_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >This field is used for queries of operation type Delete. If this checkbox is checked, the records marked for deletion are &quot;hard deleted&quot;, meaning they cannot be recovered from the recycle bin.</description>
    <inlineHelpText
  >Used for queries of operation type Delete. If this checkbox is checked, the records marked for deletion are &quot;hard deleted&quot;, meaning they cannot be recovered from the recycle bin.</inlineHelpText>
    <label>Hard Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Query__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description
  >This field describes whether the query is active or not. Only active query records will be considered in ex. the scheduled delete job.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Query__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>The primary object the query is used on.</description>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Queries</relationshipLabel>
    <relationshipName>Queries</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Query__mdt/fields/Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>Operation_Type__c</fullName>
    <description
  >Used to describe what operation type is performed on this query if applicable.</description>
    <label>Operation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MassDeleteSchedulable.cls
/**
 * @description       : This schedulable class deletes all records defined by queries in the custom metadata
 *                    : type Query. It calls the batchable class DeleteRecordsBatchable to perform the record deletion.
 * @author            : erlend.hansen@stretch.no | https://trailblazer.me/id/ehansen7
 * @last modified on  : 08-29-2022
 * @last modified by  : erlend.hansen@stretch.no | https://trailblazer.me/id/ehansen7
 **/
public virtual without sharing class MassDeleteSchedulable implements Schedulable {
  // We are unable to insert custom metadata in test class therefor we make it visible for the test class to set on init.
  @testVisible
  List<Query__mdt> allQueries {
    get {
      if (allQueries == null) {
        allQueries = Query__mdt.getAll().values();
      }
      return allQueries;
    }
    set;
  }

  public void execute(SchedulableContext sc) {
    // Get all active Delete-Queries

    List<Query__mdt> deleteQueries = new List<Query__mdt>();
    for (Query__mdt q : allQueries) {
      if (q.IsActive__c && q.Operation_Type__c == 'Delete') {
        deleteQueries.add(q);
      }
    }

    // Trigger the batchable delete-class for each query.
    for (Query__mdt q : deleteQueries) {
      String queryString =
        'SELECT Id FROM ' +
        q.Object__c +
        ' WHERE ' +
        q.Condition__c;
      Boolean hardDelete = q.Is_Hard_Delete__c;

      MassDeleteBatchable b = new MassDeleteBatchable(queryString, hardDelete);
      Database.executeBatch(b);
    }
  }
}